name: baltogui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - ipywidgets=7.5.1
  - ipyleaflet=0.13.0
  - pydap=3.2.2
  - time=1.8
  - requests=2.24.0
  - matplotlib=3.2.2
  - scipy=1.4.1
  - cartopy=0.18.0
  - urllib3=1.25.9
